version: "3.9"
services:
  mongo:
    container_name: "mernshortlydb"
    image: mongo:5.0.8-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - shortlydata:/data/db
volumes:
  shortlydata:
    driver: local
      